version: '3'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 80:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
  
  app:
    container_name: ingestao-app
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    command: /bin/bash -c "sleep 15 && python main.py"
