version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 80:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network
  
  app:
    container_name: ingestao-app
    volumes:
      - ./data:/app/data
      - ./ingestaoBI/app:/app
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    command: /bin/bash -c "sleep 10 && python main.py"

networks:
  app-network:
    driver: bridge